import type { GroceryItem } from '@/types/grocery'

/** Mock output for the generation demo. Display-only; no math happens here. */
export const MOCK_GENERATED_ITEMS: GroceryItem[] = [
  {
    id: 'ai-1',
    name: 'Milk (2L)',
    price: '240',
    quantity: 2,
    category: 'dairy',
    paidBy: '',
    sharedBy: [],
    notes: '',
  },
  {
    id: 'ai-2',
    name: 'Eggs (dozen)',
    price: '360',
    quantity: 1,
    category: 'dairy',
    paidBy: '',
    sharedBy: [],
    notes: '',
  },
  {
    id: 'ai-3',
    name: 'Brown bread',
    price: '180',
    quantity: 2,
    category: 'bakery',
    paidBy: '',
    sharedBy: [],
    notes: '',
  },
  {
    id: 'ai-4',
    name: 'Butter',
    price: '320',
    quantity: 1,
    category: 'dairy',
    paidBy: '',
    sharedBy: [],
    notes: '',
  },
  {
    id: 'ai-5',
    name: 'Orange juice (1L)',
    price: '260',
    quantity: 1,
    category: 'beverages',
    paidBy: '',
    sharedBy: [],
    notes: '',
  },
]
