import type { HistorySession } from '@/types/history'

/** Mock data for visual display only. */
export const initialHistory: HistorySession[] = [
  {
    id: 'h-1',
    title: 'Weekly restock',
    day: '24',
    monthShort: 'Jul',
    dateLabel: 'Friday, Jul 24',
    monthLabel: 'July 2026',
    sortKey: '2026-07-24',
    members: ['Aisha Khan', 'Bilal Ahmed', 'Chloe Lee', 'Daniyal Raza'],
    total: '2840',
    status: 'completed',
    settlement: 'settled',
    payments: [],
    items: [
      { name: 'Milk (2L)', category: 'dairy', price: '240', paidBy: 'Aisha Khan' },
      { name: 'Basmati rice (5kg)', category: 'pantry', price: '1450', paidBy: 'Bilal Ahmed' },
      { name: 'Apples (1kg)', category: 'produce', price: '180', paidBy: 'Chloe Lee' },
      { name: 'Dish soap', category: 'household', price: '220', paidBy: 'Aisha Khan' },
    ],
    notes: '',
  },
  {
    id: 'h-2',
    title: 'Midweek top-up',
    day: '17',
    monthShort: 'Jul',
    dateLabel: 'Friday, Jul 17',
    monthLabel: 'July 2026',
    sortKey: '2026-07-17',
    members: ['Aisha Khan', 'Bilal Ahmed', 'Chloe Lee'],
    total: '1120',
    status: 'completed',
    settlement: 'pending',
    payments: [{ from: 'Bilal Ahmed', to: 'Aisha Khan', amount: '380' }],
    items: [
      { name: 'Eggs (dozen)', category: 'dairy', price: '210', paidBy: 'Chloe Lee' },
      { name: 'Bread loaf', category: 'bakery', price: '160', paidBy: 'Aisha Khan' },
      { name: 'Orange juice', category: 'beverages', price: '340', paidBy: 'Aisha Khan' },
    ],
    notes: '',
  },
  {
    id: 'h-3',
    title: 'Weekend cookout haul',
    day: '10',
    monthShort: 'Jul',
    dateLabel: 'Friday, Jul 10',
    monthLabel: 'July 2026',
    sortKey: '2026-07-10',
    members: ['Aisha Khan', 'Bilal Ahmed', 'Chloe Lee', 'Daniyal Raza', 'Fatima Noor'],
    total: '4360',
    status: 'completed',
    settlement: 'settled',
    payments: [],
    items: [
      { name: 'Charcoal bag', category: 'household', price: '450', paidBy: 'Daniyal Raza' },
      { name: 'Chicken (2kg)', category: 'pantry', price: '1380', paidBy: 'Bilal Ahmed' },
      { name: 'Soft drinks (pack)', category: 'beverages', price: '620', paidBy: 'Fatima Noor' },
      { name: 'Buns', category: 'bakery', price: '210', paidBy: 'Aisha Khan' },
    ],
    notes: 'Flatmates + Fatima joined for the BBQ.',
  },
  {
    id: 'h-4',
    title: 'Rainy day errand',
    day: '03',
    monthShort: 'Jul',
    dateLabel: 'Friday, Jul 3',
    monthLabel: 'July 2026',
    sortKey: '2026-07-03',
    members: ['Aisha Khan', 'Bilal Ahmed', 'Chloe Lee', 'Daniyal Raza'],
    total: '1980',
    status: 'completed',
    settlement: 'pending',
    payments: [
      { from: 'Daniyal Raza', to: 'Aisha Khan', amount: '260' },
      { from: 'Chloe Lee', to: 'Aisha Khan', amount: '145' },
    ],
    items: [
      { name: 'Instant noodles (pack)', category: 'pantry', price: '320', paidBy: 'Aisha Khan' },
      { name: 'Tomatoes (1kg)', category: 'produce', price: '150', paidBy: 'Daniyal Raza' },
    ],
    notes: '',
  },
  {
    id: 'h-5',
    title: 'Pantry refresh',
    day: '26',
    monthShort: 'Jun',
    dateLabel: 'Friday, Jun 26',
    monthLabel: 'June 2026',
    sortKey: '2026-06-26',
    members: ['Aisha Khan', 'Chloe Lee', 'Daniyal Raza'],
    total: '1540',
    status: 'completed',
    settlement: 'settled',
    payments: [],
    items: [
      { name: 'Cooking oil (2L)', category: 'pantry', price: '680', paidBy: 'Chloe Lee' },
      { name: 'Lentils (1kg)', category: 'pantry', price: '210', paidBy: 'Aisha Khan' },
      { name: 'Yogurt tub', category: 'dairy', price: '190', paidBy: 'Daniyal Raza' },
    ],
    notes: '',
  },
  {
    id: 'h-6',
    title: 'Quick coffee run',
    day: '12',
    monthShort: 'Jun',
    dateLabel: 'Friday, Jun 12',
    monthLabel: 'June 2026',
    sortKey: '2026-06-12',
    members: ['Aisha Khan', 'Bilal Ahmed'],
    total: '640',
    status: 'in-progress',
    settlement: 'pending',
    payments: [{ from: 'Bilal Ahmed', to: 'Aisha Khan', amount: '320' }],
    items: [{ name: 'Coffee beans (500g)', category: 'beverages', price: '640', paidBy: 'Aisha Khan' }],
    notes: 'Cart still open, waiting on Bilal to add snacks.',
  },
  {
    id: 'h-7',
    title: 'Start-of-month shop',
    day: '01',
    monthShort: 'Jun',
    dateLabel: 'Monday, Jun 1',
    monthLabel: 'June 2026',
    sortKey: '2026-06-01',
    members: ['Aisha Khan', 'Bilal Ahmed', 'Chloe Lee', 'Daniyal Raza'],
    total: '3010',
    status: 'completed',
    settlement: 'settled',
    payments: [],
    items: [
      { name: 'Basmati rice (5kg)', category: 'pantry', price: '1450', paidBy: 'Bilal Ahmed' },
      { name: 'Milk (2L)', category: 'dairy', price: '240', paidBy: 'Aisha Khan' },
      { name: 'Dish soap', category: 'household', price: '220', paidBy: 'Chloe Lee' },
      { name: 'Bananas (dozen)', category: 'produce', price: '140', paidBy: 'Daniyal Raza' },
    ],
    notes: '',
  },
  {
    id: 'h-8',
    title: 'Grill night groceries',
    day: '22',
    monthShort: 'May',
    dateLabel: 'Friday, May 22',
    monthLabel: 'May 2026',
    sortKey: '2026-05-22',
    members: ['Aisha Khan', 'Bilal Ahmed', 'Chloe Lee', 'Daniyal Raza'],
    total: '2210',
    status: 'completed',
    settlement: 'settled',
    payments: [],
    items: [
      { name: 'Beef skewers', category: 'pantry', price: '1120', paidBy: 'Daniyal Raza' },
      { name: 'Lemonade (pack)', category: 'beverages', price: '380', paidBy: 'Bilal Ahmed' },
    ],
    notes: '',
  },
  {
    id: 'h-9',
    title: 'Small top-up',
    day: '08',
    monthShort: 'May',
    dateLabel: 'Friday, May 8',
    monthLabel: 'May 2026',
    sortKey: '2026-05-08',
    members: ['Aisha Khan', 'Chloe Lee', 'Daniyal Raza'],
    total: '980',
    status: 'completed',
    settlement: 'pending',
    payments: [{ from: 'Daniyal Raza', to: 'Chloe Lee', amount: '145' }],
    items: [
      { name: 'Apples (1kg)', category: 'produce', price: '180', paidBy: 'Chloe Lee' },
      { name: 'Croissants (4pk)', category: 'bakery', price: '260', paidBy: 'Aisha Khan' },
    ],
    notes: '',
  },
]
